// LifeQuest: Real Life RPG - Centralized Mock Data

window.BOSS_DEFINITIONS = [
  {
    id: 'sleep-nightmare',
    name: '睡眠夢魘 😴',
    icon: '😴',
    description: '連續睡眠不足讓夢魘甦醒。用穩定且充足的睡眠削弱牠。',
    maxHp: 100,
    priority: 100,
    rewards: { gold: 150, gems: 3 },
    challenge: {
      title: '連續 3 天睡滿 7 小時',
      source: 'dailyLog',
      conditions: [{ metric: 'sleep', operator: '>=', targetValue: 7 }],
      target: 3
    }
  },
  {
    id: 'budget-vampire',
    name: '預算吸血鬼 👿',
    icon: '👿',
    description: '近期支出超過設定預算，預算吸血鬼正在吞噬你的金幣。',
    maxHp: 100,
    priority: 90,
    rewards: { gold: 150, gems: 3 },
    challenge: {
      title: '連續 3 天控制在預算內且零衝動消費',
      source: 'dailyLog',
      conditions: [
        { metric: 'expense', operator: '<=', setting: 'dailyBudget' },
        { metric: 'impulse', operator: '==', targetValue: 0 }
      ],
      target: 3
    }
  },
  {
    id: 'fried-food-beast',
    name: '油炸暴食獸 🍔',
    icon: '🍔',
    description: '近期油炸垃圾食物紀錄過多。持續避開油炸物才能恢復健康。',
    maxHp: 100,
    priority: 85,
    rewards: { gold: 150, gems: 3 },
    challenge: {
      title: '連續 3 個日誌日沒有油炸垃圾食物紀錄',
      source: 'habitEvents',
      habitKey: 'fried_food',
      operator: '==',
      targetValue: 0,
      target: 3
    }
  },
  {
    id: 'laziness-beast',
    name: '怠惰巨獸 🥔',
    icon: '🥔',
    description: '連續活動量不足喚醒了怠惰巨獸。用規律運動重新取回活力。',
    maxHp: 100,
    priority: 80,
    rewards: { gold: 150, gems: 3 },
    challenge: {
      title: '連續 3 天運動至少 30 分鐘',
      source: 'dailyLog',
      conditions: [{ metric: 'exercise', operator: '>=', targetValue: 30 }],
      target: 3
    }
  },
  {
    id: 'sugar-monster',
    name: '糖分魔獸 🥤',
    icon: '🥤',
    description: '近期含糖飲料攝取次數過多。減少糖飲紀錄才能擊退牠。',
    maxHp: 100,
    priority: 75,
    rewards: { gold: 150, gems: 3 },
    challenge: {
      title: '連續 3 天沒有飲用含糖飲料',
      source: 'dailyLog',
      conditions: [{ metric: 'sugaryDrinks', operator: '==', targetValue: 0 }],
      target: 3
    }
  }
];

window.RULES_MOCK_DATA = {
  presetRules: [
    {
      id: 'rule_1',
      name: '每天睡滿七小時',
      type: 'daily',
      typeName: '公會任務',
      category: 'health',
      categoryName: '健康',
      conditionText: '睡眠時間 >= 7 小時',
      metric: 'sleep',
      operator: '>=',
      targetValue: 7,
      period: 'daily',
      exp: 20,
      gold: 5,
      attrName: 'Energy',
      attrVal: 2,
      buffName: '🌞 精神飽滿',
      duration: 1,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_2',
      name: '理性消費',
      type: 'daily',
      typeName: '公會任務',
      category: 'wealth',
      categoryName: '金錢',
      conditionText: '支出 <= 500 且無衝動消費',
      conditions: [
        { metric: 'expense', operator: '<=', targetValue: 500 },
        { metric: 'impulse', operator: '==', targetValue: 0 }
      ],
      period: 'daily',
      exp: 15,
      gold: 10,
      attrName: 'Wealth',
      attrVal: 2,
      buffName: '',
      duration: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_water',
      name: '每日飲水 2000ml',
      type: 'daily',
      typeName: '公會任務',
      category: 'health',
      categoryName: '健康',
      conditionText: '飲水量 >= 2000ml',
      metric: 'water',
      operator: '>=',
      targetValue: 2000,
      period: 'daily',
      exp: 10,
      gold: 5,
      attrName: 'Health',
      attrVal: 1,
      buffName: '',
      duration: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_exercise',
      name: '每日運動 30 分鐘',
      type: 'daily',
      typeName: '公會任務',
      category: 'health',
      categoryName: '健康',
      conditionText: '運動時間 >= 30 分鐘',
      metric: 'exercise',
      operator: '>=',
      targetValue: 30,
      period: 'daily',
      exp: 15,
      gold: 5,
      attrName: 'Energy',
      attrVal: 1,
      buffName: '',
      duration: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_5',
      name: '每日研習 30 分鐘',
      type: 'daily',
      typeName: '公會任務',
      category: 'growth',
      categoryName: '成長',
      conditionText: '研習時間 >= 30 分鐘',
      metric: 'study',
      operator: '>=',
      targetValue: 30,
      period: 'daily',
      exp: 15,
      gold: 5,
      attrName: 'Growth',
      attrVal: 2,
      buffName: '',
      duration: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_3',
      name: '連續兩天睡眠不足',
      type: 'debuff',
      typeName: '詛咒',
      category: 'health',
      categoryName: '健康',
      conditionText: '連續兩天睡眠 < 6 小時',
      metric: 'sleep',
      operator: '<',
      targetValue: 6,
      consecutive: 2,
      period: 'daily',
      exp: 0,
      gold: 0,
      attrName: 'Energy',
      attrVal: -3,
      buffName: '睡眠不足',
      duration: 1,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_boss_sleep',
      name: '連續三天極度睡眠不足',
      type: 'boss',
      typeName: '習慣魔獸',
      bossId: 'sleep-nightmare',
      category: 'health',
      categoryName: '健康',
      conditionText: '連續三天睡眠 < 5 小時',
      metric: 'sleep',
      operator: '<',
      targetValue: 5,
      consecutive: 3,
      period: 'daily',
      exp: 0,
      gold: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_boss_lazy',
      name: '連續三天活動量不足',
      type: 'boss',
      typeName: '習慣魔獸',
      bossId: 'laziness-beast',
      category: 'health',
      categoryName: '健康',
      conditionText: '連續三天運動 < 15 分鐘',
      metric: 'exercise',
      operator: '<',
      targetValue: 15,
      consecutive: 3,
      period: 'daily',
      exp: 0,
      gold: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_boss_budget',
      name: '七天支出超過週預算',
      type: 'boss',
      typeName: '習慣魔獸',
      bossId: 'budget-vampire',
      category: 'wealth',
      categoryName: '金錢',
      conditionText: '7天總支出 > 每日預算 × 7',
      metric: 'expense',
      operator: '>',
      targetValue: 3500,
      dynamicTarget: 'weeklyBudget',
      period: 'weekly',
      aggregate: 'sum',
      exp: 0,
      gold: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_boss_fried_food',
      name: '七天內三次油炸垃圾食物',
      type: 'boss',
      typeName: '習慣魔獸',
      bossId: 'fried-food-beast',
      category: 'health',
      categoryName: '健康',
      conditionText: '7天內油炸垃圾食物紀錄 >= 3 次',
      source: 'habitEvents',
      habitKey: 'fried_food',
      operator: '>=',
      targetValue: 3,
      period: 'weekly',
      aggregate: 'count',
      exp: 0,
      gold: 0,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_4',
      name: '七天飲用五次含糖飲料',
      type: 'boss',
      typeName: '習慣魔獸',
      bossId: 'sugar-monster',
      category: 'health',
      categoryName: '健康',
      conditionText: '7天內含糖飲料次數 >= 5 次',
      metric: 'sugaryDrinks',
      operator: '>=',
      targetValue: 5,
      period: 'weekly',
      aggregate: 'sum',
      exp: 0,
      gold: 0,
      attrName: '',
      attrVal: 0,
      buffName: '糖分魔獸',
      duration: 3,
      enabled: true,
      isSystem: true
    },
    {
      id: 'rule_6',
      name: '連續 3 天運動達標',
      type: 'achievement',
      typeName: '勳章',
      category: 'health',
      categoryName: '健康',
      conditionText: '連續 3 天運動 >= 30 分鐘',
      metric: 'exercise',
      operator: '>=',
      targetValue: 30,
      consecutive: 3,
      period: 'daily',
      exp: 50,
      gold: 30,
      attrName: 'Health',
      attrVal: 5,
      buffName: '🏃 活力充沛',
      duration: 2,
      achievementId: 'exercise_streak_3',
      enabled: true,
      isSystem: true
    }
  ],
  aiRecommendations: []
};
